export enum ACTIONS {
  SAVE_WORD = "SAVE_WORD",
  DELETE_WORD = "DELETE_WORD",
  LOAD_WORDS = "LOAD_WORDS",
  LOAD_AUDIO = "LOAD_AUDIO",
  ADD_WORDS_CSV = "ADD_WORDS_CSV",
  LOAD_SETTINGS = "LOAD_SETTINGS",
  LOAD_VOICES = "LOAD_VOICES",
  CHANGE_SETTINGS = "CHANGE_SETTINGS",
}
